language: ruby
cache: bundler

matrix:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      env:
        - RUBYOPT=--jit
    - rvm: ruby-head
    - rvm: jruby-19mode
      jdk: oraclejdk11
    - rvm: jruby-19mode
      jdk: oraclejdk8
    - rvm: jruby-head
      jdk: oraclejdk11
    - rvm: jruby-head
      jdk: oraclejdk8
    - rvm: truffleruby
      jdk: oraclejdk11
    - rvm: truffleruby
      jdk: oraclejdk8

before_install:
  - gem update --system
  - gem install bundler -v '< 2' #because... why
